spring:
jpa:
  hibernate:
    ddl-auto: none
  properties:
    hibernate:
      dialect: org.hibernate.dialect.H2Dialect
      format_sql: true
sql:
  init:
    mode: always
datasource:
  driver-class-name: org.h2.Driver
  url: jdbc:h2:file:./db/shareit
  username: test
  password: test
h2:
  console:
    enabled: true

logging:
  level:
    org:
      springframework:
        orm:
          jpa: INFO
          jpa.JpaTransactionManager: DEBUG
        transaction: INFO
        transaction.interceptor: TRACE