--TRUNCATE TABLE items RESTART IDENTITY CASCADE;
--TRUNCATE TABLE users RESTART IDENTITY CASCADE;
--TRUNCATE TABLE bookings RESTART IDENTITY CASCADE;

DELETE FROM comments;
DELETE FROM bookings;
DELETE FROM items;
DELETE FROM users;
